apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: jan15u7gg-python 
  janus-idp.io/tekton: jan15u7gg-python
  backstage.io/kubernetes-id: jan15u7gg-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: jan15u7gg-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  