apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: jan15u7gg-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: jan15u7gg-python 
  name: jan15u7gg-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: jan15u7gg-python 
